# Generated by Django 2.2.5 on 2021-04-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('auther', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_auther', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acvtie', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('sold', 'sold')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_name_of_clint', models.CharField(max_length=50)),
                ('the_number_phone_of_clint', models.CharField(max_length=155)),
                ('the_Email_of_clint', models.EmailField(max_length=254)),
                ('the_address_of_clint', models.CharField(max_length=50)),
                ('the_city_of_clint', models.CharField(max_length=50)),
                ('the_name_of_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qiaser_app.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qiaser_app.Category'),
        ),
    ]
